const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.TileMovement,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.Text,
		C3.Plugins.Keyboard,
		C3.Plugins.Spritefont2,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Acts.AddVar
	];
};
self.C3_JsPropNameTable = [
	{Sprite: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{TileMovement: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{moon: 0},
	{background: 0},
	{Touch: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{info: 0},
	{restart: 0},
	{outline1: 0},
	{Sprite7: 0},
	{Audio: 0},
	{Text: 0},
	{Keyboard: 0},
	{Text2: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{song: 0},
	{outline2: 0},
	{qno: 0},
	{SSS: 0},
	{SAS: 0},
	{AAS: 0},
	{HL: 0},
	{outline3: 0},
	{Sprite6: 0},
	{disclaimer: 0},
	{Sprite12: 0},
	{correctanswer: 0},
	{question: 0},
	{numberofcompletedsupports: 0}
];

self.InstanceType = {
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	moon: class extends self.ISpriteInstance {},
	background: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	info: class extends self.ISpriteInstance {},
	restart: class extends self.ISpriteInstance {},
	outline1: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Text: class extends self.ITextInstance {},
	Keyboard: class extends self.IInstance {},
	Text2: class extends self.ITextInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	song: class extends self.ITextInstance {},
	outline2: class extends self.ISpriteInstance {},
	qno: class extends self.ITextInstance {},
	SSS: class extends self.ITextInstance {},
	SAS: class extends self.ITextInstance {},
	AAS: class extends self.ITextInstance {},
	HL: class extends self.ITextInstance {},
	outline3: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	disclaimer: class extends self.ISpriteFontInstance {},
	Sprite12: class extends self.ISpriteInstance {}
}